service: aws-nodejs-typescript-test

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
          Resource:
            - { "Fn::GetAtt": ["ProductsTable", "Arn"] }

functions:
  createProduct:
    handler: src/presentation/api/create-product.handler
    events:
      - httpApi:
          path: /products
          method: post

  getProduct:
    handler: src/presentation/api/get-product.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: get

  getProducts:
    handler: src/presentation/api/get-products.handler
    events:
      - httpApi:
          path: /products
          method: get

  updateProduct:
    handler: src/presentation/api/update-product.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: put

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
